/**
 * Regenerate column-schema artifacts from `src/schema/columns/index.ts`.
 *
 * Reads the COLUMN_REGISTRY and emits:
 *   - `src/types/column-options.generated.ts` — flat per-bucket TS
 *     interfaces (`TextBucketOptions`, `NumericBucketOptions`,
 *     `PercentBucketOptions`, …).
 *   - `../R/schema-defaults.R` — one R list of effective defaults per
 *     registry key; read by R `col_*` helpers.
 *
 * Usage: `bun run scripts/regenerate-schema.ts`
 *
 * CI drift check: re-run; assert no diff vs checked-in output. Same
 * pattern as `regenerate-theme-presets.ts`.
 *
 * Why TS-canonical: per CLAUDE.md, `@tabviz/core` (TS) is the canonical
 * authoring surface. R reads from the generated `R/schema-defaults.R`
 * — no privileged R-side declaration of column-type metadata.
 */

import { writeFileSync } from "fs";
import { resolve } from "path";
import { COLUMN_REGISTRY } from "../src/schema/columns";
import { resolveLayers } from "../src/schema/resolve";
import type { OptionSpec, ColumnTypeSpec } from "../src/schema/types";

// ────────────────────────────────────────────────────────────────────
// Effective-defaults resolution
// ────────────────────────────────────────────────────────────────────

/**
 * Walk the resolved layers (BASE → leaf); later-layer options shadow
 * earlier ones with the same key. `layerOverrides` lets a column type
 * adjust a default contributed by an ancestor (e.g. percent overriding
 * numeric's `decimals=2` to `decimals=1`).
 */
function effectiveOptions(col: ColumnTypeSpec): Map<string, OptionSpec> {
  const out = new Map<string, OptionSpec>();
  for (const layer of resolveLayers(col)) {
    for (const opt of layer.options) {
      const clone: OptionSpec = { ...opt };
      const override = col.layerOverrides?.[layer.key]?.[opt.key];
      if (override !== undefined) {
        clone.default = override as never;
      }
      out.set(opt.key, clone);
    }
  }
  return out;
}

// ────────────────────────────────────────────────────────────────────
// TS interface emission
// ────────────────────────────────────────────────────────────────────

/**
 * For each bucket, collect the union of bucket-targeted options across
 * all columns using that bucket. Yields one interface per bucket.
 */
function emitBucketInterfaces(): string {
  const byBucket = new Map<string, Map<string, OptionSpec>>();
  for (const col of Object.values(COLUMN_REGISTRY)) {
    const bucket = col.bucket;
    if (!byBucket.has(bucket)) byBucket.set(bucket, new Map());
    const bag = byBucket.get(bucket)!;
    for (const opt of effectiveOptions(col).values()) {
      const at = opt.at ?? "bucket";
      if (at !== "bucket") continue;
      // If two columns disagree on an option's type, the last writer
      // wins — flag during code review.
      bag.set(opt.key, opt);
    }
  }

  const lines: string[] = [];
  lines.push("// Generated by `bun run scripts/regenerate-schema.ts` — do not edit.");
  lines.push("// Per-bucket option interfaces for column.options[bucket].");
  lines.push("");

  for (const [bucket, bag] of [...byBucket.entries()].sort()) {
    const ifaceName = bucketInterfaceName(bucket);
    lines.push(`export interface ${ifaceName} {`);
    for (const opt of [...bag.values()].sort((a, b) => a.key.localeCompare(b.key))) {
      const tsType = optionTsType(opt);
      lines.push(`  /** ${opt.label}${opt.hint ? ` — ${opt.hint}` : ""} */`);
      lines.push(`  ${opt.key}?: ${tsType};`);
    }
    lines.push("}");
    lines.push("");
  }

  return lines.join("\n");
}

function bucketInterfaceName(bucket: string): string {
  return bucket.split("-").map((p) => p[0].toUpperCase() + p.slice(1)).join("") + "BucketOptions";
}

function optionTsType(opt: OptionSpec): string {
  switch (opt.control) {
    case "toggle":
      // thousandsSep: wire type is `string | false`; editor toggle picks.
      if (opt.key === "thousandsSep") return "string | false";
      return "boolean";
    case "number":
      return 'number | "auto" | null';
    case "integer":
      return "number | null";
    case "text":
    case "color":
    case "field":
    case "select":
      return "string | null";
    case "segmented":
      if (opt.segments?.length) {
        return opt.segments.map((s) => JSON.stringify(s.value)).join(" | ") + " | null";
      }
      return "string | null";
    case "slider":
      return "number | null";
    case "custom":
      return "unknown";
  }
}

// ────────────────────────────────────────────────────────────────────
// R defaults emission
// ────────────────────────────────────────────────────────────────────

function emitRDefaults(): string {
  const lines: string[] = [];
  lines.push("# Generated by `bun run scripts/regenerate-schema.ts` — do not edit.");
  lines.push("# Read by R column constructors (col_text, col_numeric, ...) to fill");
  lines.push("# default argument values. Source of truth: srcjs/src/schema/.");
  lines.push("");
  lines.push("schema_defaults <- list(");

  const entries: string[] = [];
  for (const [key, col] of [...Object.entries(COLUMN_REGISTRY)].sort()) {
    const optsList: string[] = [];
    for (const opt of effectiveOptions(col).values()) {
      // R lists use NULL for null/undefined defaults. Skip null defaults
      // entirely — they're indistinguishable from absent in R.
      if (opt.default === null || opt.default === undefined) continue;
      optsList.push(`    ${rArgName(opt.key)} = ${rLiteral(opt.default)}`);
    }
    entries.push(`  ${key} = list(\n${optsList.join(",\n")}\n  )`);
  }

  lines.push(entries.join(",\n"));
  lines.push(")");
  lines.push("");

  return lines.join("\n");
}

/** Convert camelCase option key to R snake_case argument name. */
function rArgName(camel: string): string {
  return camel.replace(/[A-Z]/g, (c) => `_${c.toLowerCase()}`);
}

function rLiteral(v: unknown): string {
  if (v === true) return "TRUE";
  if (v === false) return "FALSE";
  if (v === null) return "NULL";
  if (typeof v === "number") return String(v);
  if (typeof v === "string") return JSON.stringify(v);
  if (Array.isArray(v)) return `c(${v.map(rLiteral).join(", ")})`;
  throw new Error(`rLiteral: unsupported value ${JSON.stringify(v)}`);
}

// ────────────────────────────────────────────────────────────────────
// Main
// ────────────────────────────────────────────────────────────────────

const here = import.meta.dir;
const tsOut = resolve(here, "../src/types/column-options.generated.ts");
const rOut  = resolve(here, "../../R/schema-defaults.R");

writeFileSync(tsOut, emitBucketInterfaces());
writeFileSync(rOut, emitRDefaults());

console.log(`✓ ${tsOut}`);
console.log(`✓ ${rOut}`);
console.log(`  ${Object.keys(COLUMN_REGISTRY).length} column types, ` +
            `${new Set(Object.values(COLUMN_REGISTRY).map(c => c.bucket)).size} buckets`);
