// Generated by `bun run scripts/regenerate-schema.ts` — do not edit.
// Per-bucket option interfaces for column.options[bucket].

export interface BarBucketOptions {
  /** Border — Column divider weight — theme decides exact value */
  borderClass?: undefined;
  /** Bar color — Theme primary by default */
  color?: string | null;
  /** Max value — Bar 100% reference; auto from data when null */
  maxValue?: number | "auto" | null;
  /** Density — Cell padding — theme decides exact values */
  paddingClass?: undefined;
  /** Scale */
  scale?: "linear" | "log" | "sqrt" | null;
  /** Show value — Numeric label alongside the bar */
  showLabel?: boolean;
  /** Token — Semantic role — theme decides colors/weights */
  token?: undefined;
}

export interface CustomBucketOptions {
  /** Abbreviate — "12.3K", "1.2M" */
  abbreviate?: boolean;
  /** Border — Column divider weight — theme decides exact value */
  borderClass?: undefined;
  /** Decimals — Decimal places. Leave blank for auto. */
  decimals?: number | null;
  /** Sig. digits — Significant figures (overrides decimals) */
  digits?: number | null;
  /** Font class — Theme decides which family / weight / numeric variant */
  fontClass?: undefined;
  /** Max chars — Truncate with trailing ellipsis when over */
  maxChars?: number | null;
  /** Density — Cell padding — theme decides exact values */
  paddingClass?: undefined;
  /** Prefix — Prepended literal (e.g. "$") */
  prefix?: string | null;
  /** Separator */
  separator?: string | null;
  /** Show percent — Append "(37.5%)" after the ratio */
  showPct?: boolean;
  /** Suffix — Appended literal (e.g. "%") */
  suffix?: string | null;
  /** Thousands sep */
  thousandsSep?: string | false;
  /** Token — Semantic role — theme decides colors/weights */
  token?: undefined;
}

export interface DateBucketOptions {
  /** Border — Column divider weight — theme decides exact value */
  borderClass?: undefined;
  /** Format — strftime-style format string */
  format?: string | null;
  /** Density — Cell padding — theme decides exact values */
  paddingClass?: undefined;
  /** Token — Semantic role — theme decides colors/weights */
  token?: undefined;
}

export interface HeatmapBucketOptions {
  /** Abbreviate — "12.3K", "1.2M" */
  abbreviate?: boolean;
  /** Border — Column divider weight — theme decides exact value */
  borderClass?: undefined;
  /** Decimals — Decimal places. Leave blank for auto. */
  decimals?: number | null;
  /** Sig. digits — Significant figures (overrides decimals) */
  digits?: number | null;
  /** Font class — Theme decides which family / weight / numeric variant */
  fontClass?: undefined;
  /** Max chars — Truncate with trailing ellipsis when over */
  maxChars?: number | null;
  /** Max value — Color-scale ceiling; auto from data when null */
  maxValue?: number | "auto" | null;
  /** Min value — Color-scale floor; auto from data when null */
  minValue?: number | "auto" | null;
  /** Density — Cell padding — theme decides exact values */
  paddingClass?: undefined;
  /** Palette — 2+ hex stops; interpolated by value */
  palette?: unknown;
  /** Prefix — Prepended literal (e.g. "$") */
  prefix?: string | null;
  /** Scale */
  scale?: "linear" | "log" | "sqrt" | null;
  /** Show value — Numeric label over the color cell */
  showValue?: boolean;
  /** Suffix — Appended literal (e.g. "%") */
  suffix?: string | null;
  /** Thousands sep */
  thousandsSep?: string | false;
  /** Token — Semantic role — theme decides colors/weights */
  token?: undefined;
}

export interface IntervalBucketOptions {
  /** Abbreviate — "12.3K", "1.2M" */
  abbreviate?: boolean;
  /** Border — Column divider weight — theme decides exact value */
  borderClass?: undefined;
  /** Decimals — Decimal places. Leave blank for auto. */
  decimals?: number | null;
  /** Sig. digits — Significant figures (overrides decimals) */
  digits?: number | null;
  /** Font class — Theme decides which family / weight / numeric variant */
  fontClass?: undefined;
  /** Imprecise cutoff — Show "—" when upper/lower > threshold */
  impreciseThreshold?: number | "auto" | null;
  /** Max chars — Truncate with trailing ellipsis when over */
  maxChars?: number | null;
  /** Density — Cell padding — theme decides exact values */
  paddingClass?: undefined;
  /** Prefix — Prepended literal (e.g. "$") */
  prefix?: string | null;
  /** Separator — Between point and bracket */
  separator?: string | null;
  /** Suffix — Appended literal (e.g. "%") */
  suffix?: string | null;
  /** Thousands sep */
  thousandsSep?: string | false;
  /** Token — Semantic role — theme decides colors/weights */
  token?: undefined;
}

export interface NumericBucketOptions {
  /** Abbreviate — "12.3K", "1.2M" */
  abbreviate?: boolean;
  /** Border — Column divider weight — theme decides exact value */
  borderClass?: undefined;
  /** Decimals — Decimal places. Leave blank for auto. */
  decimals?: number | null;
  /** Sig. digits — Significant figures (overrides decimals) */
  digits?: number | null;
  /** Font class — Theme decides which family / weight / numeric variant */
  fontClass?: undefined;
  /** Max chars — Truncate with trailing ellipsis when over */
  maxChars?: number | null;
  /** Density — Cell padding — theme decides exact values */
  paddingClass?: undefined;
  /** Position */
  position?: "prefix" | "suffix" | null;
  /** Prefix — Prepended literal (e.g. "$") */
  prefix?: string | null;
  /** Suffix — Appended literal (e.g. "%") */
  suffix?: string | null;
  /** Symbol — Currency symbol */
  symbol?: string | null;
  /** Thousands sep */
  thousandsSep?: string | false;
  /** Token — Semantic role — theme decides colors/weights */
  token?: undefined;
}

export interface PercentBucketOptions {
  /** Abbreviate — "12.3K", "1.2M" */
  abbreviate?: boolean;
  /** Border — Column divider weight — theme decides exact value */
  borderClass?: undefined;
  /** Decimals — Decimal places. Leave blank for auto. */
  decimals?: number | null;
  /** Sig. digits — Significant figures (overrides decimals) */
  digits?: number | null;
  /** Font class — Theme decides which family / weight / numeric variant */
  fontClass?: undefined;
  /** Max chars — Truncate with trailing ellipsis when over */
  maxChars?: number | null;
  /** Multiply ×100 — Off if the source field is already a percentage */
  multiply?: boolean;
  /** Density — Cell padding — theme decides exact values */
  paddingClass?: undefined;
  /** Prefix — Prepended literal (e.g. "$") */
  prefix?: string | null;
  /** Suffix — Appended literal (e.g. "%") */
  suffix?: string | null;
  /** Show "%" */
  symbol?: boolean;
  /** Thousands sep */
  thousandsSep?: string | false;
  /** Token — Semantic role — theme decides colors/weights */
  token?: undefined;
}

export interface ProgressBucketOptions {
  /** Border — Column divider weight — theme decides exact value */
  borderClass?: undefined;
  /** Fill color — Theme primary by default */
  color?: string | null;
  /** Max value — Track 100% reference */
  maxValue?: number | "auto" | null;
  /** Density — Cell padding — theme decides exact values */
  paddingClass?: undefined;
  /** Scale */
  scale?: "linear" | "log" | "sqrt" | null;
  /** Show value */
  showLabel?: boolean;
  /** Token — Semantic role — theme decides colors/weights */
  token?: undefined;
}

export interface PvalueBucketOptions {
  /** Abbrev. threshold — Values below show as "<threshold" */
  abbrevThreshold?: number | "auto" | null;
  /** Border — Column divider weight — theme decides exact value */
  borderClass?: undefined;
  /** Sig. digits */
  digits?: number | null;
  /** Exp. threshold — Values below use scientific notation */
  expThreshold?: number | "auto" | null;
  /** Format */
  format?: "auto" | "decimal" | "scientific" | null;
  /** Density — Cell padding — theme decides exact values */
  paddingClass?: undefined;
  /** Stars — Show significance stars */
  stars?: boolean;
  /** Star thresholds */
  thresholds?: unknown;
  /** Token — Semantic role — theme decides colors/weights */
  token?: undefined;
}

export interface RangeBucketOptions {
  /** Abbreviate — "12.3K", "1.2M" */
  abbreviate?: boolean;
  /** Border — Column divider weight — theme decides exact value */
  borderClass?: undefined;
  /** Decimals — Decimal places. Leave blank for auto. */
  decimals?: number | null;
  /** Sig. digits — Significant figures (overrides decimals) */
  digits?: number | null;
  /** Font class — Theme decides which family / weight / numeric variant */
  fontClass?: undefined;
  /** Max chars — Truncate with trailing ellipsis when over */
  maxChars?: number | null;
  /** Density — Cell padding — theme decides exact values */
  paddingClass?: undefined;
  /** Prefix — Prepended literal (e.g. "$") */
  prefix?: string | null;
  /** Separator */
  separator?: string | null;
  /** Show bar — Mini horizontal range bar next to the text */
  showBar?: boolean;
  /** Suffix — Appended literal (e.g. "%") */
  suffix?: string | null;
  /** Thousands sep */
  thousandsSep?: string | false;
  /** Token — Semantic role — theme decides colors/weights */
  token?: undefined;
}

export interface SparklineBucketOptions {
  /** Border — Column divider weight — theme decides exact value */
  borderClass?: undefined;
  /** Color — Theme primary by default */
  color?: string | null;
  /** Height */
  height?: number | null;
  /** Density — Cell padding — theme decides exact values */
  paddingClass?: undefined;
  /** Token — Semantic role — theme decides colors/weights */
  token?: undefined;
  /** Type */
  type?: "line" | "bar" | "area" | null;
}

export interface TextBucketOptions {
  /** Border — Column divider weight — theme decides exact value */
  borderClass?: undefined;
  /** Font class — Theme decides which family / weight / numeric variant */
  fontClass?: undefined;
  /** Max chars — Truncate with trailing ellipsis when over */
  maxChars?: number | null;
  /** Density — Cell padding — theme decides exact values */
  paddingClass?: undefined;
  /** Token — Semantic role — theme decides colors/weights */
  token?: undefined;
}
