// Generated by `bun run scripts/regenerate-schema.ts` — do not edit.
// Per-bucket option interfaces for column.options[bucket].

export interface NumericBucketOptions {
  /** Abbreviate — "12.3K", "1.2M" */
  abbreviate?: boolean;
  /** Decimals — Decimal places. Leave blank for auto. */
  decimals?: number | null;
  /** Sig. digits — Significant figures (overrides decimals) */
  digits?: number | null;
  /** Italic — Static / mapped to a data column / default */
  italic?: undefined;
  /** Max chars — Truncate with trailing ellipsis when over */
  maxChars?: number | null;
  /** Prefix — Prepended literal (e.g. "$") */
  prefix?: string | null;
  /** Suffix — Appended literal (e.g. "%") */
  suffix?: string | null;
  /** Thousands sep */
  thousandsSep?: string | false;
}

export interface PercentBucketOptions {
  /** Abbreviate — "12.3K", "1.2M" */
  abbreviate?: boolean;
  /** Decimals — Decimal places. Leave blank for auto. */
  decimals?: number | null;
  /** Sig. digits — Significant figures (overrides decimals) */
  digits?: number | null;
  /** Italic — Static / mapped to a data column / default */
  italic?: undefined;
  /** Max chars — Truncate with trailing ellipsis when over */
  maxChars?: number | null;
  /** Multiply ×100 — Off if the source field is already a percentage */
  multiply?: boolean;
  /** Prefix — Prepended literal (e.g. "$") */
  prefix?: string | null;
  /** Suffix — Appended literal (e.g. "%") */
  suffix?: string | null;
  /** Show "%" */
  symbol?: boolean;
  /** Thousands sep */
  thousandsSep?: string | false;
}

export interface TextBucketOptions {
  /** Italic — Static / mapped to a data column / default */
  italic?: undefined;
  /** Max chars — Truncate with trailing ellipsis when over */
  maxChars?: number | null;
}
