// Generated by `bun run scripts/regenerate-schema.ts` — do not edit.
// Per-bucket option interfaces for column.options[bucket].

export interface BadgeBucketOptions {
  /** Custom colors */
  colors?: unknown;
  /** Outline — Transparent fill, colored border */
  outline?: boolean;
  /** Density — Cell padding — theme decides exact values */
  paddingClass?: undefined;
  /** Shape */
  shape?: "pill" | "circle" | "square" | null;
  /** Size */
  size?: "sm" | "base" | null;
  /** Numeric thresholds — Bin numeric values into colored badges */
  thresholds?: unknown;
  /** Token — Semantic role — theme decides colors/weights */
  token?: undefined;
  /** Variants — e.g. {published: "success", draft: "warning"} */
  variants?: unknown;
}

export interface BarBucketOptions {
  /** Bar color — Theme primary by default */
  color?: string | null;
  /** Max value — Bar 100% reference; auto from data when null */
  maxValue?: number | "auto" | null;
  /** Density — Cell padding — theme decides exact values */
  paddingClass?: undefined;
  /** Scale */
  scale?: "linear" | "log" | "sqrt" | null;
  /** Show value — Numeric label alongside the bar */
  showLabel?: boolean;
  /** Token — Semantic role — theme decides colors/weights */
  token?: undefined;
}

export interface CustomBucketOptions {
  /** Abbreviate — "12.3K", "1.2M" */
  abbreviate?: boolean;
  /** Decimals — Decimal places. Leave blank for auto. */
  decimals?: number | null;
  /** Sig. digits — Significant figures (overrides decimals) */
  digits?: number | null;
  /** Font class — Theme decides which family / weight / numeric variant */
  fontClass?: undefined;
  /** Max chars — Truncate with trailing ellipsis when over */
  maxChars?: number | null;
  /** Density — Cell padding — theme decides exact values */
  paddingClass?: undefined;
  /** Prefix — Prepended literal (e.g. "$") */
  prefix?: string | null;
  /** Separator */
  separator?: string | null;
  /** Show percent — Append "(37.5%)" after the ratio */
  showPct?: boolean;
  /** Suffix — Appended literal (e.g. "%") */
  suffix?: string | null;
  /** Thousands sep */
  thousandsSep?: string | false;
  /** Token — Semantic role — theme decides colors/weights */
  token?: undefined;
}

export interface DateBucketOptions {
  /** Format — strftime-style format string */
  format?: string | null;
  /** Density — Cell padding — theme decides exact values */
  paddingClass?: undefined;
  /** Token — Semantic role — theme decides colors/weights */
  token?: undefined;
}

export interface ForestBucketOptions {
  /** Annotations — Reference lines, callouts */
  annotations?: unknown;
  /** Gridlines */
  axisGridlines?: boolean;
  /** Axis label — Shown below the axis */
  axisLabel?: string | null;
  /** Axis range — Auto from data when null */
  axisRange?: unknown;
  /** Axis ticks — Auto-computed when null */
  axisTicks?: unknown;
  /** Effects — Multiple overlaid effects; use slots above for a single effect */
  effects?: unknown;
  /** Null value — Reference line; 0 for linear, 1 for log default */
  nullValue?: number | "auto" | null;
  /** Density — Cell padding — theme decides exact values */
  paddingClass?: undefined;
  /** Scale */
  scale?: "linear" | "log" | null;
  /** Shared axis — Across split-view columns */
  sharedAxis?: boolean;
  /** Show axis */
  showAxis?: boolean;
  /** Token — Semantic role — theme decides colors/weights */
  token?: undefined;
}

export interface HeatmapBucketOptions {
  /** Abbreviate — "12.3K", "1.2M" */
  abbreviate?: boolean;
  /** Decimals — Decimal places. Leave blank for auto. */
  decimals?: number | null;
  /** Sig. digits — Significant figures (overrides decimals) */
  digits?: number | null;
  /** Font class — Theme decides which family / weight / numeric variant */
  fontClass?: undefined;
  /** Max chars — Truncate with trailing ellipsis when over */
  maxChars?: number | null;
  /** Max value — Color-scale ceiling; auto from data when null */
  maxValue?: number | "auto" | null;
  /** Min value — Color-scale floor; auto from data when null */
  minValue?: number | "auto" | null;
  /** Density — Cell padding — theme decides exact values */
  paddingClass?: undefined;
  /** Palette — 2+ hex stops; interpolated by value */
  palette?: unknown;
  /** Prefix — Prepended literal (e.g. "$") */
  prefix?: string | null;
  /** Scale */
  scale?: "linear" | "log" | "sqrt" | null;
  /** Show value — Numeric label over the color cell */
  showValue?: boolean;
  /** Suffix — Appended literal (e.g. "%") */
  suffix?: string | null;
  /** Thousands sep */
  thousandsSep?: string | false;
  /** Token — Semantic role — theme decides colors/weights */
  token?: undefined;
}

export interface IconBucketOptions {
  /** Color — Theme content by default */
  color?: string | null;
  /** Value → icon — e.g. {pass: "✓", fail: "✗"} */
  mapping?: unknown;
  /** Density — Cell padding — theme decides exact values */
  paddingClass?: undefined;
  /** Size */
  size?: "sm" | "base" | "lg" | "xl" | null;
  /** Token — Semantic role — theme decides colors/weights */
  token?: undefined;
}

export interface ImgBucketOptions {
  /** Fallback text — Shown when the URL fails to load */
  fallback?: string | null;
  /** Height — Pixels; auto from row height when null */
  height?: number | null;
  /** Max width — Pixels; auto when null */
  maxWidth?: number | null;
  /** Density — Cell padding — theme decides exact values */
  paddingClass?: undefined;
  /** Shape */
  shape?: "square" | "rounded" | "circle" | null;
  /** Token — Semantic role — theme decides colors/weights */
  token?: undefined;
}

export interface IntervalBucketOptions {
  /** Abbreviate — "12.3K", "1.2M" */
  abbreviate?: boolean;
  /** Decimals — Decimal places. Leave blank for auto. */
  decimals?: number | null;
  /** Sig. digits — Significant figures (overrides decimals) */
  digits?: number | null;
  /** Font class — Theme decides which family / weight / numeric variant */
  fontClass?: undefined;
  /** Imprecise cutoff — Show "—" when upper/lower > threshold */
  impreciseThreshold?: number | "auto" | null;
  /** Max chars — Truncate with trailing ellipsis when over */
  maxChars?: number | null;
  /** Density — Cell padding — theme decides exact values */
  paddingClass?: undefined;
  /** Prefix — Prepended literal (e.g. "$") */
  prefix?: string | null;
  /** Separator — Between point and bracket */
  separator?: string | null;
  /** Suffix — Appended literal (e.g. "%") */
  suffix?: string | null;
  /** Thousands sep */
  thousandsSep?: string | false;
  /** Token — Semantic role — theme decides colors/weights */
  token?: undefined;
}

export interface NumericBucketOptions {
  /** Abbreviate — "12.3K", "1.2M" */
  abbreviate?: boolean;
  /** Decimals — Decimal places. Leave blank for auto. */
  decimals?: number | null;
  /** Sig. digits — Significant figures (overrides decimals) */
  digits?: number | null;
  /** Font class — Theme decides which family / weight / numeric variant */
  fontClass?: undefined;
  /** Max chars — Truncate with trailing ellipsis when over */
  maxChars?: number | null;
  /** Density — Cell padding — theme decides exact values */
  paddingClass?: undefined;
  /** Prefix — Prepended literal (e.g. "$") */
  prefix?: string | null;
  /** Suffix — Appended literal (e.g. "%") */
  suffix?: string | null;
  /** Thousands sep */
  thousandsSep?: string | false;
  /** Token — Semantic role — theme decides colors/weights */
  token?: undefined;
}

export interface PercentBucketOptions {
  /** Abbreviate — "12.3K", "1.2M" */
  abbreviate?: boolean;
  /** Decimals — Decimal places. Leave blank for auto. */
  decimals?: number | null;
  /** Sig. digits — Significant figures (overrides decimals) */
  digits?: number | null;
  /** Font class — Theme decides which family / weight / numeric variant */
  fontClass?: undefined;
  /** Max chars — Truncate with trailing ellipsis when over */
  maxChars?: number | null;
  /** Multiply ×100 — Off if the source field is already a percentage */
  multiply?: boolean;
  /** Density — Cell padding — theme decides exact values */
  paddingClass?: undefined;
  /** Prefix — Prepended literal (e.g. "$") */
  prefix?: string | null;
  /** Suffix — Appended literal (e.g. "%") */
  suffix?: string | null;
  /** Show "%" */
  symbol?: boolean;
  /** Thousands sep */
  thousandsSep?: string | false;
  /** Token — Semantic role — theme decides colors/weights */
  token?: undefined;
}

export interface PictogramBucketOptions {
  /** Filled color — Theme accent by default */
  color?: string | null;
  /** Input range — Remap [min, max] → [0, maxGlyphs] */
  domain?: unknown;
  /** Empty color — Theme muted by default */
  emptyColor?: string | null;
  /** Glyph — Registry key (person, leaf, star, …) */
  glyph?: string | null;
  /** Glyph field — Per-row glyph selection */
  glyphField?: string | null;
  /** Half-step glyphs */
  halfGlyphs?: boolean;
  /** Label decimals */
  labelDecimals?: number | null;
  /** Label format */
  labelFormat?: "integer" | "decimal" | null;
  /** Layout */
  layout?: "row" | "stack" | null;
  /** Max glyphs — Rating-mode cap; null = use raw value as count */
  maxGlyphs?: number | null;
  /** Density — Cell padding — theme decides exact values */
  paddingClass?: undefined;
  /** Glyph size */
  size?: "sm" | "base" | "lg" | null;
  /** Token — Semantic role — theme decides colors/weights */
  token?: undefined;
  /** Value label */
  valueLabel?: false | true | "leading" | "trailing" | null;
}

export interface ProgressBucketOptions {
  /** Fill color — Theme primary by default */
  color?: string | null;
  /** Max value — Track 100% reference */
  maxValue?: number | "auto" | null;
  /** Density — Cell padding — theme decides exact values */
  paddingClass?: undefined;
  /** Scale */
  scale?: "linear" | "log" | "sqrt" | null;
  /** Show value */
  showLabel?: boolean;
  /** Token — Semantic role — theme decides colors/weights */
  token?: undefined;
}

export interface PvalueBucketOptions {
  /** Abbrev. threshold — Values below show as "<threshold" */
  abbrevThreshold?: number | "auto" | null;
  /** Sig. digits */
  digits?: number | null;
  /** Exp. threshold — Values below use scientific notation */
  expThreshold?: number | "auto" | null;
  /** Format */
  format?: "auto" | "decimal" | "scientific" | null;
  /** Density — Cell padding — theme decides exact values */
  paddingClass?: undefined;
  /** Significant — Paint a soft positive pill on significant values (p < first threshold). */
  significantStyle?: "none" | "pill" | null;
  /** Stars — Show significance stars */
  stars?: boolean;
  /** Stars color — Color channel for significance stars */
  starsColor?: "accent" | "ink2" | "negative" | "none" | null;
  /** Star thresholds */
  thresholds?: unknown;
  /** Token — Semantic role — theme decides colors/weights */
  token?: undefined;
}

export interface RangeBucketOptions {
  /** Abbreviate — "12.3K", "1.2M" */
  abbreviate?: boolean;
  /** Decimals — Decimal places. Leave blank for auto. */
  decimals?: number | null;
  /** Sig. digits — Significant figures (overrides decimals) */
  digits?: number | null;
  /** Font class — Theme decides which family / weight / numeric variant */
  fontClass?: undefined;
  /** Max chars — Truncate with trailing ellipsis when over */
  maxChars?: number | null;
  /** Density — Cell padding — theme decides exact values */
  paddingClass?: undefined;
  /** Prefix — Prepended literal (e.g. "$") */
  prefix?: string | null;
  /** Separator */
  separator?: string | null;
  /** Suffix — Appended literal (e.g. "%") */
  suffix?: string | null;
  /** Thousands sep */
  thousandsSep?: string | false;
  /** Token — Semantic role — theme decides colors/weights */
  token?: undefined;
}

export interface ReferenceBucketOptions {
  /** Font class — Theme decides which family / weight / numeric variant */
  fontClass?: undefined;
  /** URL field — Optional column with URLs to link */
  hrefField?: string | null;
  /** Max chars — Truncate with trailing ellipsis when over */
  maxChars?: number | null;
  /** Density — Cell padding — theme decides exact values */
  paddingClass?: undefined;
  /** Link icon — External-link indicator when URL is present */
  showIcon?: boolean;
  /** Token — Semantic role — theme decides colors/weights */
  token?: undefined;
}

export interface RingBucketOptions {
  /** Filled color — Theme accent by default; thresholds switch color */
  color?: string | null;
  /** Label decimals */
  labelDecimals?: number | null;
  /** Label format */
  labelFormat?: "percent" | "decimal" | "integer" | null;
  /** Max value */
  maxValue?: number | "auto" | null;
  /** Min value */
  minValue?: number | "auto" | null;
  /** Density — Cell padding — theme decides exact values */
  paddingClass?: undefined;
  /** Show label */
  showLabel?: boolean;
  /** Ring size */
  size?: "sm" | "base" | "lg" | null;
  /** Color thresholds — Breakpoints where the arc color shifts */
  thresholds?: unknown;
  /** Token — Semantic role — theme decides colors/weights */
  token?: undefined;
  /** Track color — Theme muted by default */
  trackColor?: string | null;
}

export interface SparklineBucketOptions {
  /** Color — Theme primary by default */
  color?: string | null;
  /** Height */
  height?: number | null;
  /** Density — Cell padding — theme decides exact values */
  paddingClass?: undefined;
  /** Token — Semantic role — theme decides colors/weights */
  token?: undefined;
  /** Type */
  type?: "line" | "bar" | "area" | null;
}

export interface StarsBucketOptions {
  /** Filled color — Theme accent by default */
  color?: string | null;
  /** Input range — Remap [min, max] → [0, maxGlyphs] */
  domain?: unknown;
  /** Empty color — Theme muted by default */
  emptyColor?: string | null;
  /** Glyph — Registry key (person, leaf, star, …) */
  glyph?: string | null;
  /** Glyph field — Per-row glyph selection */
  glyphField?: string | null;
  /** Half-step glyphs */
  halfGlyphs?: boolean;
  /** Label decimals */
  labelDecimals?: number | null;
  /** Label format */
  labelFormat?: "integer" | "decimal" | null;
  /** Layout */
  layout?: "row" | "stack" | null;
  /** Max glyphs — Rating-mode cap; null = use raw value as count */
  maxGlyphs?: number | null;
  /** Density — Cell padding — theme decides exact values */
  paddingClass?: undefined;
  /** Glyph size */
  size?: "sm" | "base" | "lg" | null;
  /** Token — Semantic role — theme decides colors/weights */
  token?: undefined;
  /** Value label */
  valueLabel?: false | true | "leading" | "trailing" | null;
}

export interface TextBucketOptions {
  /** Font class — Theme decides which family / weight / numeric variant */
  fontClass?: undefined;
  /** Max chars — Truncate with trailing ellipsis when over */
  maxChars?: number | null;
  /** Density — Cell padding — theme decides exact values */
  paddingClass?: undefined;
  /** Token — Semantic role — theme decides colors/weights */
  token?: undefined;
}

export interface VizBarBucketOptions {
  /** Annotations — Reference lines, callouts */
  annotations?: unknown;
  /** Gridlines */
  axisGridlines?: boolean;
  /** Axis label — Shown below the axis */
  axisLabel?: string | null;
  /** Axis range — Auto from data when null */
  axisRange?: unknown;
  /** Axis ticks — Auto-computed when null */
  axisTicks?: unknown;
  /** Effects — One or more value series */
  effects?: unknown;
  /** Null value — Reference line; 0 for linear, 1 for log default */
  nullValue?: number | "auto" | null;
  /** Density — Cell padding — theme decides exact values */
  paddingClass?: undefined;
  /** Scale */
  scale?: "linear" | "log" | null;
  /** Shared axis — Across split-view columns */
  sharedAxis?: boolean;
  /** Show axis */
  showAxis?: boolean;
  /** Token — Semantic role — theme decides colors/weights */
  token?: undefined;
}

export interface VizBoxplotBucketOptions {
  /** Annotations — Reference lines, callouts */
  annotations?: unknown;
  /** Gridlines */
  axisGridlines?: boolean;
  /** Axis label — Shown below the axis */
  axisLabel?: string | null;
  /** Axis range — Auto from data when null */
  axisRange?: unknown;
  /** Axis ticks — Auto-computed when null */
  axisTicks?: unknown;
  /** Effects — Raw arrays or quantile fields */
  effects?: unknown;
  /** Null value — Reference line; 0 for linear, 1 for log default */
  nullValue?: number | "auto" | null;
  /** Density — Cell padding — theme decides exact values */
  paddingClass?: undefined;
  /** Scale */
  scale?: "linear" | "log" | null;
  /** Shared axis — Across split-view columns */
  sharedAxis?: boolean;
  /** Show axis */
  showAxis?: boolean;
  /** Show outliers */
  showOutliers?: boolean;
  /** Token — Semantic role — theme decides colors/weights */
  token?: undefined;
}

export interface VizViolinBucketOptions {
  /** Annotations — Reference lines, callouts */
  annotations?: unknown;
  /** Gridlines */
  axisGridlines?: boolean;
  /** Axis label — Shown below the axis */
  axisLabel?: string | null;
  /** Axis range — Auto from data when null */
  axisRange?: unknown;
  /** Axis ticks — Auto-computed when null */
  axisTicks?: unknown;
  /** Bandwidth — KDE bandwidth; Silverman default when null */
  bandwidth?: number | "auto" | null;
  /** Effects — One or more array-valued series */
  effects?: unknown;
  /** Null value — Reference line; 0 for linear, 1 for log default */
  nullValue?: number | "auto" | null;
  /** Density — Cell padding — theme decides exact values */
  paddingClass?: undefined;
  /** Scale */
  scale?: "linear" | "log" | null;
  /** Shared axis — Across split-view columns */
  sharedAxis?: boolean;
  /** Show axis */
  showAxis?: boolean;
  /** Show median */
  showMedian?: boolean;
  /** Show quartiles */
  showQuartiles?: boolean;
  /** Token — Semantic role — theme decides colors/weights */
  token?: undefined;
}
