# Generated by `bun run scripts/regenerate-schema.ts` — do not edit.
# Read by R column constructors (col_text, col_numeric, ...) to fill
# default argument values. Source of truth: srcjs/src/schema/.

schema_defaults <- list(
  numeric = list(
    align = "left",
    width = "auto",
    wrap = FALSE,
    decimals = 2,
    thousands_sep = FALSE,
    abbreviate = FALSE,
    sortable = TRUE
  ),
  percent = list(
    align = "left",
    width = "auto",
    wrap = FALSE,
    decimals = 1,
    thousands_sep = FALSE,
    abbreviate = FALSE,
    multiply = TRUE,
    symbol = TRUE,
    sortable = TRUE
  ),
  text = list(
    align = "left",
    width = "auto",
    wrap = FALSE,
    sortable = TRUE
  )
)
