# Generated by `bun run scripts/regenerate-schema.ts` — do not edit.
# Read by R column constructors (col_text, col_numeric, ...) to fill
# default argument values. Source of truth: srcjs/src/schema/.

schema_defaults <- list(
  badge = list(
    align = "left",
    width = "auto",
    sortable = TRUE,
    size = "base",
    shape = "pill",
    outline = FALSE
  ),
  bar = list(
    align = "left",
    width = "auto",
    sortable = TRUE,
    scale = "linear",
    show_label = TRUE
  ),
  currency = list(
    align = "left",
    width = "auto",
    sortable = TRUE,
    wrap = FALSE,
    decimals = 2,
    thousands_sep = ",",
    abbreviate = FALSE
  ),
  date = list(
    align = "left",
    width = "auto",
    sortable = TRUE,
    format = "%Y-%m-%d"
  ),
  events = list(
    header = "Events",
    align = "left",
    width = "auto",
    sortable = TRUE,
    wrap = FALSE,
    decimals = 2,
    thousands_sep = ",",
    abbreviate = FALSE,
    separator = "/",
    show_pct = FALSE
  ),
  heatmap = list(
    align = "left",
    width = "auto",
    sortable = TRUE,
    wrap = FALSE,
    decimals = 2,
    thousands_sep = FALSE,
    abbreviate = FALSE,
    palette = c("#f7fbff", "#08306b"),
    show_value = TRUE,
    scale = "linear"
  ),
  icon = list(
    align = "left",
    width = "auto",
    sortable = TRUE,
    size = "base"
  ),
  img = list(
    align = "left",
    width = "auto",
    sortable = FALSE,
    fallback = "[img]",
    shape = "square"
  ),
  interval = list(
    header = "95% CI",
    align = "left",
    width = "auto",
    sortable = TRUE,
    wrap = FALSE,
    decimals = 2,
    thousands_sep = FALSE,
    abbreviate = FALSE,
    separator = " "
  ),
  n = list(
    header = "N",
    align = "left",
    width = "auto",
    sortable = TRUE,
    wrap = FALSE,
    decimals = 0,
    thousands_sep = ",",
    abbreviate = FALSE
  ),
  numeric = list(
    align = "left",
    width = "auto",
    sortable = TRUE,
    wrap = FALSE,
    decimals = 2,
    thousands_sep = FALSE,
    abbreviate = FALSE
  ),
  percent = list(
    align = "left",
    width = "auto",
    sortable = TRUE,
    wrap = FALSE,
    decimals = 1,
    thousands_sep = FALSE,
    abbreviate = FALSE,
    multiply = TRUE,
    symbol = TRUE
  ),
  pictogram = list(
    align = "left",
    width = "auto",
    sortable = TRUE,
    glyph = "person",
    half_glyphs = FALSE,
    size = "base",
    layout = "row",
    value_label = FALSE,
    label_decimals = 1
  ),
  progress = list(
    align = "left",
    width = "auto",
    sortable = TRUE,
    max_value = 100,
    scale = "linear",
    show_label = TRUE
  ),
  pvalue = list(
    header = "P-value",
    align = "left",
    width = "auto",
    sortable = TRUE,
    stars = FALSE,
    stars_color = "accent",
    significant_style = "none",
    format = "auto",
    digits = 2,
    exp_threshold = 0.001,
    thresholds = c(0.05, 0.01, 0.001)
  ),
  range = list(
    header = "Range",
    align = "left",
    width = "auto",
    sortable = TRUE,
    wrap = FALSE,
    thousands_sep = FALSE,
    abbreviate = FALSE,
    separator = " - "
  ),
  reference = list(
    header = "Reference",
    align = "left",
    width = "auto",
    sortable = TRUE,
    wrap = FALSE,
    max_chars = 30,
    show_icon = TRUE
  ),
  ring = list(
    align = "left",
    width = "auto",
    sortable = TRUE,
    min_value = 0,
    max_value = 1,
    size = "base",
    show_label = TRUE,
    label_format = "percent",
    label_decimals = 0
  ),
  sparkline = list(
    align = "left",
    width = "auto",
    sortable = FALSE,
    type = "line",
    height = 20
  ),
  stars = list(
    align = "left",
    width = "auto",
    sortable = TRUE,
    glyph = "star",
    max_glyphs = 5,
    half_glyphs = FALSE,
    size = "base",
    layout = "row",
    value_label = FALSE,
    label_decimals = 1
  ),
  text = list(
    align = "left",
    width = "auto",
    sortable = TRUE,
    wrap = FALSE
  ),
  viz_bar = list(
    align = "left",
    width = "auto",
    sortable = TRUE,
    scale = "linear",
    axis_gridlines = FALSE,
    show_axis = TRUE,
    shared_axis = FALSE,
    effects = c()
  ),
  viz_boxplot = list(
    align = "left",
    width = "auto",
    sortable = TRUE,
    scale = "linear",
    axis_gridlines = FALSE,
    show_axis = TRUE,
    shared_axis = FALSE,
    effects = c(),
    show_outliers = TRUE
  ),
  viz_forest = list(
    align = "left",
    width = "auto",
    sortable = TRUE,
    scale = "linear",
    axis_gridlines = FALSE,
    show_axis = TRUE,
    shared_axis = FALSE
  ),
  viz_violin = list(
    align = "left",
    width = "auto",
    sortable = TRUE,
    scale = "linear",
    axis_gridlines = FALSE,
    show_axis = TRUE,
    shared_axis = FALSE,
    effects = c(),
    show_median = TRUE,
    show_quartiles = FALSE
  )
)
